apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovia-k8s-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: ovia-k8s
  template:
    metadata:
      labels:
        app: ovia-k8s
    spec:
      containers:
      - name: ovia-k8s
        image: ojpascale/ovia-k8s-project:latest
        ports:
        - containerPort: 8080  

---
apiVersion: v1
kind: Service
metadata:
  name: ovia-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: ovia-k8s
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 
